### PR TITLE
option to add path to the url

### PR DESCRIPTION
**Pull request by blaisefonseca**

### CODE REVIEW

**Comment by idohalevi** [comment]
@blaisefonseca thank you.
Can you please describe the use case for this?

**Comment by blaisefonseca** [comment]
@idohalevi sorry for no description. it will be useful to specify path on domain instead of hitting the domain directly for eg. `https://logserver.com/logs-errors?token=xxxx` instead of just `https://logserver.com?token=xxxxxx`. currently we have a multi purpose log server and we would like to accept information on different paths based on the use of the service.

**Comment by idohalevi** [comment]
@blaisefonseca 
How is that a use case for a Logz.io user?

**Comment by blaisefonseca** [comment]
@idohalevi my use case was in general, as a non logzio endpoint use case. Am I mistaken that the library is intended to be used by non logzio users as well?

**Comment by idohalevi** [comment]
@blaisefonseca 
I'm sorry but yes. I can't commit we won't change anything that might cause issues if a non-Logz.io user uses it.

**Pull request closed without merging**
