### PR TITLE
refactor function `messagesToBody`

### PR DESCRIPTION
**Pull request by kleinron**
refactor function `messagesToBody` so that we first transform the messages to json and then join them.
code is a bit more readable like that.
might be better performance, since it reduces temp memory allocation.

### CODE REVIEW

**Comment by Doron-Bargo** [comment]
Hi @kleinron 
Thank you for improving our code
we will check your PR soon

**Comment by kleinron** [comment]
Hi,
Any update on this PR?
I have another fix to suggest...

**Comment by jkowall** [comment]
I'm sorry for the delay, we are going to get better and handling these in a timely manner. My colleague will review it this weekend!

**Comment by ukmadlz** [comment]
@ronish31 I just ran it through it's tests and had a look at it's performance improvement and it looks good.

**Review by ukmadlz — APPROVED** [review]

**Comment by ukmadlz** [comment]
> Hi,
> Any update on this PR?
> I have another fix to suggest...

@kleinron do you want to submit another PR with your follow up work?

**Review by ronish31 — APPROVED** [review]

**Comment by kleinron** [comment]
@ukmadlz I will :blush: :wrench:

**Pull request merged**
