### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by boofinka**
Replaced "API token" with "account token" as this is causing confusion with users.

### CODE REVIEW

**Comment by idohalevi** [comment]
@boofinka Nice catch. @imnotashrimp can you go over this?

**Comment by imnotashrimp** [comment]
This is another one I should sync with the docs—

@boofinka Can you review the docs page and let me know if anything needs updating there? I'll copy over the information once you give me the go-ahead

https://docs.logz.io/shipping/log-sources/nodejs.html

**Comment by boofinka** [comment]
Reviewed, seems good.

**Review by idohalevi — APPROVED** [review]
@imnotashrimp Feel free to merge when you're ready

**Pull request merged**
